-- Create custom types (ENUMs)
CREATE TYPE public.message_kind AS ENUM ('text', 'image', 'video', 'audio', 'code', 'structured');
CREATE TYPE public.job_status AS ENUM ('pending', 'processing', 'completed', 'failed');

-- Profiles Table
-- Stores public user data, linked to the Supabase auth.users table.
CREATE TABLE public.profiles (
    id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name TEXT,
    email TEXT,
    avatar_url TEXT,
    plan TEXT DEFAULT 'free',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
-- Comment on profiles table
COMMENT ON TABLE public.profiles IS 'Stores public user data, linked to Supabase auth.users.';

-- Function to create a profile for a new user
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name, avatar_url)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to execute the function after a new user is created
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Conversations Table
CREATE TABLE public.conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES public.profiles(id),
    title TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    is_shared BOOLEAN DEFAULT FALSE
);
CREATE INDEX ON public.conversations (owner_id);
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

-- Messages Table
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES public.profiles(id),
    kind public.message_kind NOT NULL,
    body TEXT,
    media JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX ON public.messages (conversation_id);
CREATE INDEX messages_body_idx ON public.messages USING GIN (to_tsvector('english', body));
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Jobs Table
CREATE TABLE public.jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id),
    conversation_id BIGINT REFERENCES public.conversations(id),
    status public.job_status DEFAULT 'pending' NOT NULL,
    prompt TEXT,
    inputs JSONB,
    outputs JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX ON public.jobs (user_id);
CREATE INDEX ON public.jobs (status);
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- Assets Table
CREATE TABLE public.assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES public.profiles(id),
    url TEXT NOT NULL,
    type TEXT,
    size BIGINT,
    meta JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX ON public.assets (owner_id);
ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;

-- Billing Usage Table
CREATE TABLE public.billing_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id),
    webhook_calls_count INT DEFAULT 0,
    images_created_count INT DEFAULT 0,
    video_seconds_generated INT DEFAULT 0,
    audio_seconds_generated INT DEFAULT 0,
    period_start_date TIMESTAMPTZ NOT NULL,
    period_end_date TIMESTAMPTZ NOT NULL
);
CREATE INDEX ON public.billing_usage (user_id);
ALTER TABLE public.billing_usage ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Allow public read access" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow individual update access" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Allow individual access to conversations" ON public.conversations FOR ALL USING (auth.uid() = owner_id);
CREATE POLICY "Allow access to messages in owned conversations" ON public.messages FOR ALL USING (conversation_id IN (SELECT id FROM public.conversations WHERE owner_id = auth.uid()));
CREATE POLICY "Allow individual access to jobs" ON public.jobs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Allow individual access to assets" ON public.assets FOR ALL USING (auth.uid() = owner_id);
CREATE POLICY "Allow individual access to billing" ON public.billing_usage FOR ALL USING (auth.uid() = user_id);

-- Function to update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update 'updated_at' on jobs table
CREATE TRIGGER on_job_update
BEFORE UPDATE ON public.jobs
FOR EACH ROW
EXECUTE PROCEDURE public.handle_updated_at();